(define (make-account balance password)
  (define (withdraw amount)
    (if (>= balance amount)
        (begin (set! balance (- balance amount))
               balance)
        "Insufficient funds"))
  (define (deposit amount)
    (set! balance (+ balance amount))
    balance)
  (let ((incorrect-attempts 0))
    (define (dispatch m pass)
      (if (eq? pass password)
        (begin 
          (set! incorrect-attempts 0)
          (cond ((eq? m 'withdraw) withdraw)
                ((eq? m 'deposit) deposit)
                (else (error "Unknown request -- MAKE-ACCOUNT" m))))
        (begin 
          (set! incorrect-attempts (+ incorrect-attempts 1))
          (if (>= incorrect-attempts 7)
            (error "Calling the Cops")
            (error "Incorrect Password")))))
  dispatch))

(define a (make-account 2220 'hola))

((a 'withdraw 'hola) 20)

((a 'withdraw 'hi) 20)
((a 'withdraw 'hi) 20)
((a 'withdraw 'hi) 20)
((a 'withdraw 'hi) 20)
((a 'withdraw 'hi) 20)
((a 'withdraw 'hi) 20)
((a 'withdraw 'hi) 20)

