(define (or-gate a1 a2 output)
  (define (or-action-procedure)
    (let ((b1 (make-wire))
          (b2 (make-wire)))
        (lambda () (set-signal! b1 (inverter a1))
          (set-signal! b2 (inverter a2))
          (set-signal! output (inverter (and-gate b1 b2))))))
  (add-action! a1 or-action-procedure)
  (add-action! b1 or-action-procedure)
  'ok)
