(load "stream-library.scm")
(define s (cons-stream 1 (add-streams s s)))
(define a s)
(stream-car s)
(set! s (stream-cdr s))
(stream-car s)
(set! s (stream-cdr s))
(stream-car s)
(set! s (stream-cdr s))
(stream-car s)
(set! s (stream-cdr s))
(stream-car s)
(set! s (stream-cdr s))
(stream-car s)
