(load "stream-library.scm")
(define s (cons-stream 1 (merge (scale-stream s 2) (merge (scale-stream s 3) (scale-stream s 5)))))

(stream-car s)
(set! s (stream-cdr s))
(stream-car s)
(set! s (stream-cdr s))
(stream-car s)
(set! s (stream-cdr s))
(stream-car s)
(set! s (stream-cdr s))
(stream-car s)
(set! s (stream-cdr s))
(stream-car s)
(set! s (stream-cdr s))
(stream-car s)
(set! s (stream-cdr s))
(stream-car s)
(set! s (stream-cdr s))
(stream-car s)
(set! s (stream-cdr s))
(stream-car s)
(set! s (stream-cdr s))
(stream-car s)
(set! s (stream-cdr s))
(stream-car s)
(set! s (stream-cdr s))


