(define (let*-parameters exp) (cadr exp))
(define (let*-body exp) (cddr exp))
(define (first-let* parameters) (car parameters))
(define (rest-let* parameters) (car parameters))
(define (let*->nested-lets exp)
  (define (iter parameters body)
    (cond ((null? parameters) body) 
          (else (make-let (first-let* parameters)
                          (iter (rest-let* parameters))))))
  (iter (let*-parameters exp) (let*-body exp)))
