(define (unless? exp) (tagged-list? 'unless exp))
(define (unless-condition exp) (cadr exp))
(define (unless-usual-val exp) (caddr exp))
(define (unless-exceptional-val exp)
  (if (not (null? (cdddr exp)))
      (cadddr exp)
      false))
(define (eval-unless exp env)
  (if (true? (eval (unless-condition exp) env))
      (eval (unless-exceptional-val exp) env)
      (eval (unless-usual-val exp) env)))
